### PR TITLE
Added CONTRIBUTING.md and CodeOfConduct.md

### LINKED ISSUE #1: Create a good CONTRIBUTION.md Guide
We are looking for a well defined CONTRIBUTION.md file for the Organization that will serve as common for all the Repos across the organization. It should reflect about the core values of the organization and how anyone can help us by contributing to the project.

### PR DESCRIPTION
**Pull request by ganesh-utla**
Added well-guided CONTRIBUTING.md
Added Code_Of_Coduct.md

Fixes #1 #2

### CODE REVIEW

**Comment by kunalagra** [comment]
The contribution.md should be general in sense. 
Refer to the Organization instead of Machine Learning and make the changes appropriately.

**Comment by ganesh-utla** [comment]
Please accept my PR!!

**Comment by kunalagra** [comment]
Please separate PRs for both.
Also CodeOfConduct is mixed versions of 2.1 & 1.4.
I would prefer if you stick to 2.1 version completely.

**Comment by ganesh-utla** [comment]
Yeah I've modified it.. You can check now!

**Comment by kunalagra** [comment]
Please remove/replace placeholder text.

**Comment by ganesh-utla** [comment]
Done!

**Comment by kunalagra** [comment]
Looks alot better. 
Thank you for your contribution!

**Pull request merged**
